### ISSUE TITLE
Implement Card Component

### ISSUE THREAD

**Issue by Black996** [RahafAl0/Readers-Club#1]
Implementation of  a Card Component is needed to be able to represent books each in the form of cards such as the figma design.

Requirements:
- The card should have the book cover image.
- The card should have a book title.
- The card should have an author.
- The card should show the progress in the book.
- The card should show the rating in the form of stars (out of 5).

Example: 

![Group of Cards](https://user-images.githubusercontent.com/48261136/198849007-1be7a617-a30b-4483-9dfa-fe3ea17f25b5.png)

![Single Card](https://user-images.githubusercontent.com/48261136/198849009-9f1e4b60-5669-428c-a9f4-351eb26c5bc2.png)

**Comment by RahafAl0** [comment]
Done book cover 
Done a book title.
Done card author.
Done book progress.
Done Book rating.
Working on card style.

**Comment by Black996** [comment]
the card still needs a rating view with stars icons and progress with a progress bar. Will be done on phase 2
