### ISSUE TITLE
Implement A Button Component

### ISSUE THREAD

**Issue by Black996** [RahafAl0/Readers-Club#2]
An Implementation of a button component needs to be done in order to be used in representing the buttons across the project.

Requirements:
- The button should accept a title.
- It should accept a background color.
- It should accept a font-color.

Examples:

![Add-to](https://user-images.githubusercontent.com/48261136/198849643-9f554c7e-5ae5-4c49-b11a-61ad50bb4bdb.png)
![Add-review](https://user-images.githubusercontent.com/48261136/198849670-536bd624-d62d-4d5f-939c-d87c74a70fd5.png)
![Add-book](https://user-images.githubusercontent.com/48261136/198849857-f6df4f96-61dd-46eb-bb7c-9c7ce2772122.png)

**Comment by RahafAl0** [comment]
Done button should accept a title.
Working on a button should accept a background color.
Working on a button should accept a font-color.

**Comment by RahafAl0** [comment]
Done button should accept a background color.
Done button should accept a font-color.

**Comment by Black996** [comment]
That's nice! You should adjust the padding for the button component as well for the text to be readable and user-friendly

They need a padding and a border radius.

**Comment by RahafAl0** [comment]
Done button nedded padding
