### ISSUE TITLE
Implement Status Box component

### ISSUE THREAD

**Issue by Black996** [RahafAl0/Readers-Club#3]
Implement the status box component as in figma design.

The box should accept a count as a number and a title as a string.

![Status Boxes](https://user-images.githubusercontent.com/48261136/199604434-b764c792-7913-4114-9892-decbbe3a569e.png)
![Status Box](https://user-images.githubusercontent.com/48261136/199604952-eb98c51c-954a-44a2-beaf-7e4ffa425064.png)

**Comment by RahafAl0** [comment]
Done Implement the status box component as in figma design.

Done The box should accept a count as a number and a title as a string.
